name: Docs

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install nox
      run: pip install nox==2020.12.31

    - name: Install poetry
      run: pip install poetry==1.1.4

    - name: Run nox docs session
      run: nox -s docs

    - name: Upload built docs
      uses: actions/upload-artifact@v1
      with:
        path: docs/_build
