name: CI

on:
  push:
    branches: [ main, develop, initial ]
  pull_request:
    branches: [ main, develop, initial ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    name: Python ${{ matrix.python-version }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up nox
      uses: excitedleigh/setup-nox@1.0.0

    - name: Set up poetry 1.1.4
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.4

    - name: Run nox
      run: nox
